version: "3.7"
services:
  rstudio:
    image: renv-docker-example-external-package-cache:latest
    build:
      context: _rstudio
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=password
      - DISABLE_AUTH=true
      - RENV_PATHS_CACHE=/home/rstudio/.local/share/renv/cache
    volumes:
      - .:/home/rstudio/project
      - ${RENV_PATHS_CACHE_HOST}:/home/rstudio/.local/share/renv/cache
